version: "3"

services:
  sd-webui-browser:
    build: .
    ports:
      - "7888:7888"
    volumes:
      - /data/sd-generated/:/data
      - /data/snapx/cache/:/cache
      - /data/snapx/iib.db:/db/iib.db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - IIB_ACCESS_CONTROL_ALLOWED_PATHS=/data
      - IIB_CACHE_DIR=/cache
      - IIB_DB_PATH=/db/iib.db
      - DEFAULT_APP_SSH_PRIVATE_KEY=$DEFAULT_APP_SSH_PRIVATE_KEY
      - DEFAULT_APP_HOST=$DEFAULT_APP_HOST
      - DEFAULT_APP_PATH=/Applications/Pinta.app/Contents/MacOS/Pinta
    restart: always
